# Generated by Django 4.2.3 on 2023-07-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateTimeField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(default=None, max_length=254)),
                ('address', models.TextField(max_length=250)),
                ('purpose', models.CharField(choices=[('enquiry', 'enquiry'), ('place order', 'place order'), ('return', 'return'), ('rating', 'rating')], default=None, max_length=20)),
            ],
        ),
    ]
