# Generated by Django 4.2.3 on 2023-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproapp1', '0009_alter_store_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='course',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
