# Generated by Django 4.2.3 on 2023-08-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproapp1', '0011_alter_store_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='materials',
            field=models.CharField(choices=[('book', 'Book'), (' pen', 'Pen'), ('pencil', 'Pencil'), ('exam papper', 'Exam papper'), ('chart papper', 'Chart papper'), ('instrument box', 'Instrument box')], default=None, max_length=100),
        ),
    ]
