# Generated by Django 4.2.3 on 2023-08-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproapp1', '0013_alter_store_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='materials',
            field=models.BooleanField(default=None, max_length=100),
        ),
    ]
