# Generated by Django 4.2.3 on 2023-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproapp1', '0014_alter_store_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='materials',
            field=models.JSONField(default=list),
        ),
    ]
