# Generated by Django 4.2.3 on 2023-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproapp1', '0015_alter_store_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='materials',
            field=models.CharField(choices=[('book', 'Book'), (' pen', 'Pen'), ('pencil', 'Pencil'), ('exam papper', 'Exam papper'), ('chart papper', 'Chart papper'), ('instrument box', 'Instrument box')], max_length=100, null=True),
        ),
    ]
