# Generated by Django 4.2.3 on 2023-08-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalproapp1', '0016_alter_store_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='materials',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='purpose',
            field=models.CharField(choices=[('enquiry', 'enquiry'), ('place order', 'place order'), ('return', 'return'), ('rating', 'rating')], default=None, max_length=20),
        ),
    ]
